insert into Activity (id, type, title, user, date, description) values (1, 'Doing', 'Achaogen, Inc.', 'Gnni', '2023-03-29 00:18:08', 'disintermediate seamless models');
insert into Activity (id, type, title, user, date, description) values (2, 'Todo', 'Electrum Special Acquisition Corporation', 'Ailis', '2023-09-02 23:18:08', 'reinvent web-enabled infrastructures');
insert into Activity (id, type, title, user, date, description) values (3, 'Todo', 'Western Alliance Bancorporation', 'Phillie', '2023-11-24 23:32:22', 'harness compelling e-business');
insert into Activity (id, type, title, user, date, description) values (4, 'Doing', 'FireEye, Inc.', 'Sergei', '2023-10-19 20:47:11', 'maximize proactive content');
insert into Activity (id, type, title, user, date, description) values (5, 'Todo', 'Arrow Electronics, Inc.', 'Lari', '2023-11-25 03:00:23', 'streamline integrated schemas');
insert into Activity (id, type, title, user, date, description) values (6, 'Doing', 'Wellesley Bancorp, Inc.', 'Prue', '2023-03-09 23:57:00', 'leverage seamless portals');
insert into Activity (id, type, title, user, date, description) values (7, 'Done', 'Pacific Special Acquisition Corp.', 'Odelia', '2023-06-22 23:23:01', 'grow viral portals');
insert into Activity (id, type, title, user, date, description) values (8, 'Done', 'Eastman Kodak Company', 'Dilan', '2023-09-05 14:54:25', 'grow viral action-items');
insert into Activity (id, type, title, user, date, description) values (9, 'Done', 'Laureate Education, Inc.', 'Dexter', '2023-10-15 01:20:53', 'brand out-of-the-box infomediaries');
insert into Activity (id, type, title, user, date, description) values (10, 'Todo', 'Hartford Financial Services Group, Inc. (The)', 'Patric', '2023-08-16 07:21:14', 'enable proactive convergence');
insert into Activity (id, type, title, user, date, description) values (11, 'Todo', 'Differential Brands Group Inc.', 'Janeczka', '2023-09-26 10:46:17', 'scale 24/7 convergence');
insert into Activity (id, type, title, user, date, description) values (12, 'Todo', 'Diodes Incorporated', 'Andie', '2023-06-15 01:04:40', 'disintermediate customized convergence');
insert into Activity (id, type, title, user, date, description) values (13, 'Doing', 'Poage Bankshares, Inc.', 'Francene', '2023-02-06 06:43:45', 'target frictionless applications');
insert into Activity (id, type, title, user, date, description) values (14, 'Todo', 'Trevena, Inc.', 'Maryjane', '2023-05-16 08:54:03', 'engage seamless niches');
insert into Activity (id, type, title, user, date, description) values (15, 'Doing', 'Putnam High Income Bond Fund', 'Sterne', '2023-02-14 09:51:39', 'monetize killer models');
insert into Activity (id, type, title, user, date, description) values (16, 'Doing', 'Enstar Group Limited', 'Leanor', '2023-11-02 16:17:29', 'transform ubiquitous metrics');
insert into Activity (id, type, title, user, date, description) values (17, 'Todo', 'Vishay Precision Group, Inc.', 'Knox', '2023-04-09 19:10:13', 'leverage real-time models');
insert into Activity (id, type, title, user, date, description) values (18, 'Doing', 'AK Steel Holding Corporation', 'Birk', '2023-05-24 15:08:55', 'transition plug-and-play users');
insert into Activity (id, type, title, user, date, description) values (19, 'Doing', 'Euronav NV', 'Daven', '2023-09-15 00:12:11', 'deploy customized applications');
insert into Activity (id, type, title, user, date, description) values (20, 'Done', 'Prologis, Inc.', 'Ben', '2023-05-11 11:38:44', 'transform bleeding-edge bandwidth');
insert into Activity (id, type, title, user, date, description) values (21, 'Done', 'Threshold Pharmaceuticals, Inc.', 'Wyn', '2023-03-03 23:41:34', 'incentivize B2C e-tailers');
insert into Activity (id, type, title, user, date, description) values (22, 'Doing', 'Herman Miller, Inc.', 'Jocelyn', '2023-12-16 10:41:01', 'cultivate dynamic relationships');
insert into Activity (id, type, title, user, date, description) values (23, 'Done', 'Medovex Corp.', 'Angeline', '2023-03-08 06:22:45', 'transform interactive niches');
insert into Activity (id, type, title, user, date, description) values (24, 'Done', 'The Long-Term Care ETF', 'Ailbert', '2023-11-29 23:20:43', 'evolve B2C technologies');
insert into Activity (id, type, title, user, date, description) values (25, 'Done', 'Stellar Acquisition III Inc.', 'Jacintha', '2023-01-11 05:52:17', 'utilize frictionless eyeballs');
insert into Activity (id, type, title, user, date, description) values (26, 'Todo', 'MSG Networks Inc.', 'Rey', '2023-03-10 05:18:59', 'maximize transparent applications');
insert into Activity (id, type, title, user, date, description) values (27, 'Doing', 'Copart, Inc.', 'Filip', '2023-03-30 08:30:58', 'drive seamless action-items');
insert into Activity (id, type, title, user, date, description) values (28, 'Todo', 'Cardtronics plc', 'Faustine', '2023-10-19 16:06:40', 'grow front-end web-readiness');
insert into Activity (id, type, title, user, date, description) values (29, 'Doing', 'NMI Holdings Inc', 'Quint', '2023-04-26 15:33:39', 'engage 24/365 functionalities');
insert into Activity (id, type, title, user, date, description) values (30, 'Doing', 'Ares Management L.P.', 'Raff', '2023-12-03 04:52:22', 'leverage customized networks');
insert into Activity (id, type, title, user, date, description) values (31, 'Todo', 'Citigroup Inc.', 'Junia', '2023-06-26 14:33:35', 'syndicate best-of-breed communities');
insert into Activity (id, type, title, user, date, description) values (32, 'Todo', 'Steel Partners Holdings LP', 'Jarib', '2023-02-21 14:42:27', 'disintermediate next-generation partnerships');
insert into Activity (id, type, title, user, date, description) values (33, 'Doing', 'Urban Outfitters, Inc.', 'Rosette', '2023-01-07 00:45:31', 'reinvent sexy synergies');
insert into Activity (id, type, title, user, date, description) values (34, 'Done', 'ClearBridge Energy MLP Fund Inc.', 'Noel', '2023-05-01 06:12:29', 'integrate strategic content');
insert into Activity (id, type, title, user, date, description) values (35, 'Done', 'Hexcel Corporation', 'Olympe', '2023-03-13 09:02:04', 'maximize holistic mindshare');
insert into Activity (id, type, title, user, date, description) values (36, 'Doing', 'First Trust NASDAQ-100 Ex-Technology Sector Index Fund', 'Arleta', '2023-01-29 02:34:10', 'deliver cross-platform schemas');
insert into Activity (id, type, title, user, date, description) values (37, 'Todo', 'Systemax Inc.', 'Federica', '2023-01-13 03:40:42', 'productize turn-key infrastructures');
insert into Activity (id, type, title, user, date, description) values (38, 'Done', 'Morningstar, Inc.', 'Torry', '2023-06-10 00:04:16', 'deliver ubiquitous markets');
insert into Activity (id, type, title, user, date, description) values (39, 'Done', 'Loews Corporation', 'Thoma', '2023-02-21 19:05:04', 'visualize seamless web services');
insert into Activity (id, type, title, user, date, description) values (40, 'Todo', 'BancFirst Corporation', 'Wilhelm', '2023-09-30 05:31:57', 'synergize magnetic e-services');
insert into Activity (id, type, title, user, date, description) values (41, 'Todo', 'Madrigal Pharmaceuticals, Inc.', 'Sharleen', '2023-03-08 16:38:15', 'leverage web-enabled schemas');
insert into Activity (id, type, title, user, date, description) values (42, 'Doing', 'Stryker Corporation', 'Jeffie', '2023-08-15 10:50:13', 'whiteboard front-end infrastructures');
insert into Activity (id, type, title, user, date, description) values (43, 'Todo', 'Gridsum Holding Inc.', 'Nicolais', '2023-05-15 08:39:20', 'morph end-to-end web services');
insert into Activity (id, type, title, user, date, description) values (44, 'Done', 'Jones Lang LaSalle Incorporated', 'Ichabod', '2023-12-05 10:48:03', 'redefine enterprise synergies');
insert into Activity (id, type, title, user, date, description) values (45, 'Todo', 'SandRidge Permian Trust', 'Lacee', '2023-03-11 20:16:16', 'enable front-end schemas');
insert into Activity (id, type, title, user, date, description) values (46, 'Todo', 'Boston Private Financial Holdings, Inc.', 'Fayth', '2023-11-08 11:24:30', 'transform front-end functionalities');
insert into Activity (id, type, title, user, date, description) values (47, 'Todo', 'PTC Therapeutics, Inc.', 'Julianne', '2023-06-04 08:05:10', 'recontextualize turn-key convergence');
insert into Activity (id, type, title, user, date, description) values (48, 'Done', 'Provident Financial Holdings, Inc.', 'Sibeal', '2023-07-22 03:02:29', 'aggregate next-generation infomediaries');
insert into Activity (id, type, title, user, date, description) values (49, 'Doing', 'Mitcham Industries, Inc.', 'Anthiathia', '2023-06-03 01:31:35', 'harness interactive e-tailers');
insert into Activity (id, type, title, user, date, description) values (50, 'Todo', 'Becton, Dickinson and Company', 'Germana', '2023-12-11 12:25:52', 'iterate interactive users');
insert into Activity (id, type, title, user, date, description) values (51, 'Todo', 'State Auto Financial Corporation', 'Minette', '2023-01-11 17:34:41', 'productize cross-media metrics');
insert into Activity (id, type, title, user, date, description) values (52, 'Doing', 'Verifone Systems, Inc.', 'Bil', '2023-03-06 07:26:08', 'generate B2C convergence');
insert into Activity (id, type, title, user, date, description) values (53, 'Doing', 'Patheon N.V.', 'Lorne', '2023-06-18 15:55:24', 'embrace ubiquitous vortals');
insert into Activity (id, type, title, user, date, description) values (54, 'Doing', 'Customers Bancorp, Inc', 'Saree', '2023-09-30 13:20:24', 'streamline transparent users');
insert into Activity (id, type, title, user, date, description) values (55, 'Todo', 'Ardelyx, Inc.', 'Andromache', '2023-12-10 06:19:11', 'seize plug-and-play ROI');
insert into Activity (id, type, title, user, date, description) values (56, 'Doing', 'First Trust Total US Market AlphaDEX ETF', 'Brandtr', '2023-07-25 22:22:25', 'whiteboard back-end e-markets');
insert into Activity (id, type, title, user, date, description) values (57, 'Done', 'Valley National Bancorp', 'Alford', '2023-11-02 23:55:09', 'repurpose compelling e-tailers');
insert into Activity (id, type, title, user, date, description) values (58, 'Todo', 'Northern Trust Corporation', 'Abba', '2023-02-04 16:57:23', 'leverage dynamic paradigms');
insert into Activity (id, type, title, user, date, description) values (59, 'Done', 'Luby''s, Inc.', 'Cherie', '2023-03-10 22:30:40', 'integrate B2C e-markets');
insert into Activity (id, type, title, user, date, description) values (60, 'Done', 'Premier, Inc.', 'Normand', '2023-04-28 14:22:27', 'recontextualize innovative channels');
